// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAbeZu4Czyf_Ux84S7FftzPgsmpKA9aWw4",
      authDomain: "konya-restaurant-reservation.firebaseapp.com",
      databaseURL:
          "https://konya-restaurant-reservation-default-rtdb.firebaseio.com",
      projectId: "konya-restaurant-reservation",
      storageBucket: "konya-restaurant-reservation.appspot.com",
      messagingSenderId: "601384697415",
      appId: "1:601384697415:web:93e5babf59c7694d743b62",
      measurementId: "G-KJXKCMM4EQ");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-eVIk_BOuiuDh4ZUBfsYWEUgpRZR9sAY',
    appId: '1:601384697415:android:e26ec0f78848970d743b62',
    messagingSenderId: '601384697415',
    projectId: 'konya-restaurant-reservation',
    storageBucket: 'konya-restaurant-reservation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbHG-Mo2CppTBfEDrmWsPv7_OYqXle3Fk',
    appId: '1:601384697415:ios:67bf8929ffb5901f743b62',
    messagingSenderId: '601384697415',
    projectId: 'konya-restaurant-reservation',
    storageBucket: 'konya-restaurant-reservation.appspot.com',
    iosBundleId: 'com.example.mgmt',
  );
}
